"""add_contract_sum_to_wbs_codes

Revision ID: 00b512d421ff
Revises: 20c1fe75ddf3
Create Date: 2026-05-07 15:33:29.129841
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00b512d421ff'
down_revision: Union[str, None] = '20c1fe75ddf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wbs_codes', sa.Column('contract_sum', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wbs_codes', 'contract_sum')
    # ### end Alembic commands ###
