"""initial schema

Revision ID: 20c1fe75ddf3
Revises: 
Create Date: 2026-05-07 07:34:15.923009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20c1fe75ddf3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('project_number', sa.String(length=100), nullable=True),
    sa.Column('client_name', sa.String(length=500), nullable=False),
    sa.Column('client_contact', sa.String(length=255), nullable=True),
    sa.Column('contractor_name', sa.String(length=500), nullable=False),
    sa.Column('contract_sum', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('claim_number', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('payment_due', sa.Date(), nullable=True),
    sa.Column('contractor_job_number', sa.String(length=50), nullable=True),
    sa.Column('raw_pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_contract_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variations_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('revised_contract_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('retention_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('claimed_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retention_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tier_order', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('up_to_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wbs_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('level', sa.Enum('category', 'subcategory', name='wbslevel'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['wbs_codes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'finalised', name='assessmentstatus'), nullable=False),
    sa.Column('contract_sum', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('adjustment_to_provisional_sums', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('approved_variation_orders', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('adjusted_contract_sum', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('value_claimed_to_date', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('adjustments', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_recommended', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_retention', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_payment_to_date', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('previously_certified', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('recommended_this_period', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_including_gst', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('finalised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('contract_work', 'variation', 'provisional_sum', name='claimitemtype'), nullable=False),
    sa.Column('ref_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('ptd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('previous', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('suggested_wbs_code_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['suggested_wbs_code_id'], ['wbs_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provisional_sums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ps_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('contract_sum', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('trade', sa.String(length=255), nullable=True),
    sa.Column('wbs_code_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['wbs_code_id'], ['wbs_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ci_number', sa.Integer(), nullable=False),
    sa.Column('contractor_ref', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('contractor_submission', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('unapproved', 'in_review', 'approved', name='variationstatus'), nullable=False),
    sa.Column('trade', sa.String(length=255), nullable=True),
    sa.Column('wbs_code_id', sa.UUID(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['wbs_code_id'], ['wbs_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('claim_line_item_id', sa.UUID(), nullable=True),
    sa.Column('wbs_code_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('contract_sum', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('contractor_claim_to_date', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_recommended', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('variance_to_claim', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('previously_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recommended_this_period', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unapproved', 'approved', 'interim', name='lineitemstatus'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['claim_line_item_id'], ['claim_line_items.id'], ),
    sa.ForeignKeyConstraint(['wbs_code_id'], ['wbs_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_provisional_sums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('provisional_sum_id', sa.UUID(), nullable=False),
    sa.Column('contractor_claim_to_date', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_recommended', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('variance_to_claim', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('previously_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recommended_this_period', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unapproved', 'approved', 'interim', name='lineitemstatus'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['provisional_sum_id'], ['provisional_sums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_variations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('variation_id', sa.UUID(), nullable=False),
    sa.Column('contractor_claim_to_date', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_recommended', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('variance_to_claim', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('previously_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recommended_this_period', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unapproved', 'approved', 'interim', name='lineitemstatus'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['variation_id'], ['variations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_variations')
    op.drop_table('assessment_provisional_sums')
    op.drop_table('assessment_line_items')
    op.drop_table('variations')
    op.drop_table('provisional_sums')
    op.drop_table('claim_line_items')
    op.drop_table('assessments')
    op.drop_table('wbs_codes')
    op.drop_table('retention_tiers')
    op.drop_table('claims')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
