"""add validation_warnings and confidence fields

Revision ID: 3cd6849c9008
Revises: 73aa159fee5b
Create Date: 2026-05-08 12:51:48.382800
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3cd6849c9008'
down_revision: Union[str, None] = '73aa159fee5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_line_items', sa.Column('categorisation_confidence', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('claim_line_items', sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('claims', sa.Column('validation_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'validation_warnings')
    op.drop_column('claim_line_items', 'warnings')
    op.drop_column('claim_line_items', 'categorisation_confidence')
    # ### end Alembic commands ###
