"""widen percentage columns from numeric 7 4 to 10 4

Revision ID: 55f878939228
Revises: 60e9b22d48ef
Create Date: 2026-05-19 15:37:20.048699
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55f878939228'
down_revision: Union[str, None] = '60e9b22d48ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_line_items', 'percentage',
               existing_type=sa.NUMERIC(precision=7, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('assessment_provisional_sums', 'percentage',
               existing_type=sa.NUMERIC(precision=7, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('assessment_variations', 'percentage',
               existing_type=sa.NUMERIC(precision=7, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('claim_line_items', 'percentage',
               existing_type=sa.NUMERIC(precision=7, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim_line_items', 'percentage',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=7, scale=4),
               existing_nullable=False)
    op.alter_column('assessment_variations', 'percentage',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=7, scale=4),
               existing_nullable=False)
    op.alter_column('assessment_provisional_sums', 'percentage',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=7, scale=4),
               existing_nullable=False)
    op.alter_column('assessment_line_items', 'percentage',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=7, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
