"""make_assessment_line_item_contract_sum_nullable

Revision ID: 60e9b22d48ef
Revises: 2fff457fcebf
Create Date: 2026-05-17 19:02:52.107769
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60e9b22d48ef'
down_revision: Union[str, None] = '2fff457fcebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_line_items', 'contract_sum',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_line_items', 'contract_sum',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    # ### end Alembic commands ###
