"""add_interim_adjustment_fields

Revision ID: 620bdcbf13de
Revises: 959d679ee2e3
Create Date: 2026-05-20 13:41:03.396743
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '620bdcbf13de'
down_revision: Union[str, None] = '959d679ee2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    adjustmenttype = sa.Enum('interim_adjustment', name='adjustmenttype')
    adjustmenttype.create(op.get_bind(), checkfirst=True)
    op.add_column('assessment_line_items', sa.Column('adjustment_type', adjustmenttype, nullable=True))
    op.add_column('assessment_line_items', sa.Column('source_assessment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assessment_line_items', 'assessments', ['source_assessment_id'], ['id'])
    op.add_column('assessment_provisional_sums', sa.Column('adjustment_type', adjustmenttype, nullable=True))
    op.add_column('assessment_provisional_sums', sa.Column('source_assessment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assessment_provisional_sums', 'assessments', ['source_assessment_id'], ['id'])
    op.add_column('assessment_variations', sa.Column('adjustment_type', adjustmenttype, nullable=True))
    op.add_column('assessment_variations', sa.Column('source_assessment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assessment_variations', 'assessments', ['source_assessment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessment_variations', type_='foreignkey')
    op.drop_column('assessment_variations', 'source_assessment_id')
    op.drop_column('assessment_variations', 'adjustment_type')
    op.drop_constraint(None, 'assessment_provisional_sums', type_='foreignkey')
    op.drop_column('assessment_provisional_sums', 'source_assessment_id')
    op.drop_column('assessment_provisional_sums', 'adjustment_type')
    op.drop_constraint(None, 'assessment_line_items', type_='foreignkey')
    op.drop_column('assessment_line_items', 'source_assessment_id')
    op.drop_column('assessment_line_items', 'adjustment_type')
    sa.Enum(name='adjustmenttype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
