"""add variation_id ps_id to claim_line_items and status approved_amount to provisional_sums

Revision ID: 73aa159fee5b
Revises: 00b512d421ff
Create Date: 2026-05-08 10:34:04.674326
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '73aa159fee5b'
down_revision: Union[str, None] = '00b512d421ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_line_items', sa.Column('variation_id', sa.UUID(), nullable=True))
    op.add_column('claim_line_items', sa.Column('provisional_sum_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'claim_line_items', 'variations', ['variation_id'], ['id'])
    op.create_foreign_key(None, 'claim_line_items', 'provisional_sums', ['provisional_sum_id'], ['id'])
    op.add_column('provisional_sums', sa.Column('approved_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('provisional_sums', sa.Column('status', sa.Enum('unapproved', 'in_review', 'approved', name='variationstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provisional_sums', 'status')
    op.drop_column('provisional_sums', 'approved_amount')
    op.drop_constraint(None, 'claim_line_items', type_='foreignkey')
    op.drop_constraint(None, 'claim_line_items', type_='foreignkey')
    op.drop_column('claim_line_items', 'provisional_sum_id')
    op.drop_column('claim_line_items', 'variation_id')
    # ### end Alembic commands ###
