"""add harness tables

Revision ID: 89a9f40959af
Revises: baa130a24bcf
Create Date: 2026-05-11 16:57:27.859223
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '89a9f40959af'
down_revision: Union[str, None] = 'baa130a24bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harness_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('harness_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='harness_session_status'), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=False),
    sa.Column('phase_results', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('input_file_path', sa.String(length=1000), nullable=True),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_parse_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('flag_type', sa.Enum('total_mismatch', 'over_claim', 'percentage_error', 'ptd_decrease', 'missing_ref', 'duplicate_item', 'format_warning', 'confidence_low', name='flag_type'), nullable=False),
    sa.Column('severity', sa.Enum('error', 'warning', 'info', name='flag_severity'), nullable=False),
    sa.Column('line_item_ref', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['harness_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_parse_flags_session_id'), 'claim_parse_flags', ['session_id'], unique=False)
    op.create_table('harness_workspace_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('internal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['harness_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'file_path', name='uq_workspace_session_filepath')
    )
    op.create_index(op.f('ix_harness_workspace_files_session_id'), 'harness_workspace_files', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_harness_workspace_files_session_id'), table_name='harness_workspace_files')
    op.drop_table('harness_workspace_files')
    op.drop_index(op.f('ix_claim_parse_flags_session_id'), table_name='claim_parse_flags')
    op.drop_table('claim_parse_flags')
    op.drop_table('harness_sessions')
    # ### end Alembic commands ###
