"""add country currency to users

Revision ID: 959d679ee2e3
Revises: 55f878939228
Create Date: 2026-05-20 11:10:03.714049
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '959d679ee2e3'
down_revision: Union[str, None] = '55f878939228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=2), server_default='NZ', nullable=False))
    op.add_column('users', sa.Column('currency', sa.String(length=3), server_default='NZD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
