"""replace engineer and bool split with pct split fields

Revision ID: 9ec697028edd
Revises: e0f0c2031fa8
Create Date: 2026-05-10 15:17:10.427516
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ec697028edd'
down_revision: Union[str, None] = 'e0f0c2031fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('landlord_split_pct', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('projects', sa.Column('operator_split_pct', sa.Numeric(precision=5, scale=4), nullable=True))
    op.drop_column('projects', 'engineer_to_contract')
    op.drop_column('projects', 'has_landlord_operator_split')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('has_landlord_operator_split', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('engineer_to_contract', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('projects', 'operator_split_pct')
    op.drop_column('projects', 'landlord_split_pct')
    # ### end Alembic commands ###
