"""add provisional_sum_total to projects

Revision ID: baa130a24bcf
Revises: 9ec697028edd
Create Date: 2026-05-11 16:15:09.311195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'baa130a24bcf'
down_revision: Union[str, None] = '9ec697028edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('provisional_sum_total', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'provisional_sum_total')
    # ### end Alembic commands ###
