"""add project client and claim date fields

Revision ID: e0f0c2031fa8
Revises: 3cd6849c9008
Create Date: 2026-05-10 14:57:23.307656
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0f0c2031fa8'
down_revision: Union[str, None] = '3cd6849c9008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('claim_received', sa.Date(), nullable=True))
    op.add_column('claims', sa.Column('provisional_payment_schedule_due', sa.Date(), nullable=True))
    op.add_column('claims', sa.Column('payment_schedule_due', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('end_client_name', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('end_client_representative', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('end_client_address', sa.String(length=1000), nullable=True))
    op.add_column('projects', sa.Column('engineer_to_contract', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('has_landlord_operator_split', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'has_landlord_operator_split')
    op.drop_column('projects', 'engineer_to_contract')
    op.drop_column('projects', 'end_client_address')
    op.drop_column('projects', 'end_client_representative')
    op.drop_column('projects', 'end_client_name')
    op.drop_column('claims', 'payment_schedule_due')
    op.drop_column('claims', 'provisional_payment_schedule_due')
    op.drop_column('claims', 'claim_received')
    # ### end Alembic commands ###
