"""add is_closed_out to assessment rows

Revision ID: ec5b9364608a
Revises: 620bdcbf13de
Create Date: 2026-05-21 08:15:07.951660
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec5b9364608a'
down_revision: Union[str, None] = '620bdcbf13de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_line_items', sa.Column('is_closed_out', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('assessment_provisional_sums', sa.Column('is_closed_out', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('assessment_variations', sa.Column('is_closed_out', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Backfill: set is_closed_out for rows whose comments start with "Closed Out"
    op.execute("UPDATE assessment_line_items SET is_closed_out = true WHERE comments LIKE 'Closed Out%'")
    op.execute("UPDATE assessment_variations SET is_closed_out = true WHERE comments LIKE 'Closed Out%'")
    op.execute("UPDATE assessment_provisional_sums SET is_closed_out = true WHERE comments LIKE 'Closed Out%'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_variations', 'is_closed_out')
    op.drop_column('assessment_provisional_sums', 'is_closed_out')
    op.drop_column('assessment_line_items', 'is_closed_out')
    # ### end Alembic commands ###
